
on: [push]

name: dotnetbuild

env:
  AZURE_WEBAPP_PACKAGE_PATH: '.'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout GitHub Action' 
      uses: actions/checkout@master
   
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Setup Dotnet 2.2.300
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2.300'
    
    - name: 'Run dotnet build'
      shell: bash
      run: |
        # If your web app project is not located in your repository's root
        # Please consider using pushd to change your path
        # pushd .
        dotnet build --configuration Release 
        dotnet publish -c Release 
        # popd
        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.1.4
      with:
        path: '/home/runner/work/githubactiontest'
               
    # deploy web app using Azure credentials
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'githubActionsTestCn'
        publish-profile: ${{ secrets.PUBLISH_PROFILE }}
        package: '/home/runner/work/githubactiontest/githubactiontest/githubactiontest/bin/Release/netcoreapp2.1/publish'

    # Azure logout 
    - name: logout
      run: |
        az logout
